import Footer from '@/components/Footer/Footer'
import  Header from '@/components/Header/Header'
import Landing from '@/components/Landing/Landing'
import Head from 'next/head'


export default function Home() {
  return (
    <div className='h-screen bg-slate-900 overflow-y-auto overflow-x-hidden scrollbar-thin scrollbar-thumb-slate-700 '>
      <Head>
        <title>Crogam</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


      <header>
        <Header transparent/>
      </header>


      <main>
        <Landing />
      </main>
      

     
        <Footer />
   
      
    </div>
  )
}
